[workspace]

resolver = "2"

members = ["async_pty", "frozen_term", "frostbyte_term"]

[workspace.dependencies]
anyhow = "1.0.98"
sipper = "0.1.0"
thiserror = "2.0.12"
tokio-util = { version = "0.7.15", features = ["rt"] }
